### PR TITLE
Issue fix for #911

### PR DESCRIPTION
**Pull request by ieaves**
Ref #911

### CODE REVIEW

**Comment by mhnatiuk** [comment]
any plans on pursuing this?

**Comment by mkarbo** [comment]
I am implementing this fix locally as well - any plans or updates on this?

**Comment by ieaves** [comment]
I’m currently traveling, the prior fix only failed on Python 3.8 but I don’t have time at the moment to figure out why. If anyone wants to pick things up from here they are welcome to hop in.

**Comment by ieaves** [comment]
Closing for #945

**Pull request closed without merging**
