### PR TITLE
Added link to EverythingPython Youtube video on installing pandas-profiling in a virtual environment

### PR DESCRIPTION
**Pull request by abhicantdraw**

### CODE REVIEW

**Comment by sbrugman** [comment]
Hi @abhicantdraw, thanks for the submission. Two minor things before we can merge:
- A space is missing between Jan 25, and 2022
- Please prefix the commit message with "docs: " to pass the [commitlint](https://www.conventionalcommits.org/en/v1.0.0/)

**Review by sbrugman — CHANGES_REQUESTED** [review]
See PR comment

**Comment by abhicantdraw** [comment]
@sbrugman  Done on both counts!

**Comment by abhicantdraw** [comment]
Looks like this is still a problem because of the message length. 🤦🏻‍♂️ will fix it and re-submit.

**Pull request merged**
