### PR TITLE
Fixes #638 : Added filter to browse through columns easily

### LINKED ISSUE #638: Provide ways to quickly locate a column in the HTML report
**Missing functionality**

In the situation of profiling large data frames (hundreds of columns), it is very hard to locate a specific column. It would be great if the HTML report provide a way for this. For example, provide a filtering box. When a user type in something in the filtering box, show only match columns. 

**Proposed feature**

Provide a filtering box in the HTML report. When a user type in something in the filtering box, show only match columns. 

**Alternatives considered**

**Additional context**

### PR DESCRIPTION
**Pull request by AlphaGaurav7**
I have added an input box functionality which can filter the columns for easier access to the desired column. 

image

### CODE REVIEW

**Comment by AlphaGaurav7** [comment]
Here's the functionality in action on a sample dataset profile I had made:


https://user-images.githubusercontent.com/57868024/194132419-b40f1e8c-2956-4051-8ddd-1ecc71d5eea2.mp4

**Comment by sbrugman** [comment]
Thanks for your contribution!

To fix the commitmsg lint, add a prefix "feat:" to the commit message. The message is used to construct the changelog, so it's better to have a more descriptive title that indicates that the filter is related to variables.

The linting issues can be found and partially fixed by running `pre-commit run --all-files`.

The implementation now spans the HTML reports.  Are you planning to expand it to the ipywidgets reports?

**Comment by AlphaGaurav7** [comment]
Hey @sbrugman , the best way I found to add the search bar was to directly append it to the variables section. But I think the list wants only a unique type of elements throughout for uniformity. Any way to resolve the same?

**Comment by sbrugman** [comment]
@AlphaGaurav7 add a type hint to the list of the base type: `my_list : List[Renderable] = []`

**Comment by AlphaGaurav7** [comment]
Hey @sbrugman ! I've made the required changes and updated the commit message.

**Comment by sbrugman** [comment]
@AlphaGaurav7 Could you please rebase just the last commit onto develop? Changing base left some old history there.

**Comment by fabclmnt** [comment]
@AlphaGaurav7 the commit message is failing in the linter. Can you please have changed it as per @sbrugman's request?

**Comment by AlphaGaurav7** [comment]
I have made the required changes yes, but rebasing has me confused. I haven't worked with git very often, and now have some issues pushing just one commit. Would it be better if I could switch to the develop branch, add the dropdown feature and sync before pushing? I think it'll be less of a hassle for me.

**Comment by sbrugman** [comment]
@AlphaGaurav7 If the development branch is up to date locally, you could do `git rebase --inreractive develop` (modern IDEs do have options for this if you prefer not to use CLI).

**Comment by AlphaGaurav7** [comment]
A little help needed, I'm unable to make this work. Since this PR is from the "master" branch on my end which syncs with the "master" branch on the original repo, if I take the commit from my "master" branch and rebase it to the "develop" branch on the fork which if up to date locally, should I create a new PR as it doesn't reflect in this PR?

**Comment by AlphaGaurav7** [comment]
Closing this PR, will make required changes in a proper fashion and make necessary updates and will open a new PR :+1:

**Pull request closed without merging**
