### PR TITLE
feat: added filter to locate columns

### PR DESCRIPTION
**Pull request by g-kabra**
Follow up PR to correct inconsistencies encountered in previous PR for same feature (#1101).

### CODE REVIEW

**Comment by fabclmnt** [comment]
@g-kabra after merging into `develop` I was able to identify some odd behavior in the filter:

- For some datasets, the filter was not able to locate the selected variable, which means the variables section would just "disappear" if a column was selected;
- The sections order was altered - interactions are being shown before the variables section for profiles where the minimal setting is set to False.

Uploading Screen Recording 2022-10-19 at 12.07.45 PM.mov…

**Comment by fabclmnt** [comment]
Here the report for the titanic dataset
https://user-images.githubusercontent.com/30911746/196782652-1c20ef9c-e6e4-4aed-838f-df053007a883.mov

**Comment by g-kabra** [comment]
I did find one issue in the jQuery function I had setup. Since the names were being converted to lowercase, a match wasn't being found. I have updated that and will be committing. Reviews and suggestions appreciated.

**Comment by g-kabra** [comment]
As far as the order of Interaction is concerned, I'll sort it out and commit the same.

**Comment by g-kabra** [comment]
These two issues are solved. Sorry I had overlooked these in a hurry.

**Comment by aquemy** [comment]
I checked the code from @g-kabra locally directly from his fork and it works for Titanic now.

In general, the position of the select is a bit awkward because it breaks the HTML border, but this is a cosmetic thing we might fix later.

**Review by aquemy — APPROVED** [review]

**Pull request merged**
